### ISSUE TITLE
Settings are introduced too early

### ISSUE THREAD

**Issue by PabRod** [esciencecenter-digital-skills/model-coupling-workshop#26]
## Problem

The introduction of `instance.get_setting(...)` in [episode 3](https://esciencecenter-digital-skills.github.io/lesson-model-coupling/03-muscle-connect.html#settings) (Connecting a model to MUSCLE) happens before any settings have been set. This breaks the learning rhythm.

## Suggested solution

Consider creating the settings earlier in this chapter or, alternatively, provide the learner with a settings file or `set_settings` snippet, even if its explanation has to wait until a next episode.

**Comment by LourensVeen** [comment]
This is a bit of a chicken and egg problem. The settings are set globally, as part of the coupling specification, so to the model they really do come falling from the sky. So we would have to move episode 4 to before episode 3 to do that, but then the problem is that we start talking about models before they've been introduced.

This is already explained there, do you think it would help to have a YAML snippet with example settings? It's just a dictionary, so I'm not sure it would add much, but maybe? Or maybe it would help to explain that the settings are like arguments to a function, of which you also don't know where they come from?

It's the same thing for the ports and the messages incidentally, sent messages just disappear, received messages appear out of nowhere, by design, because we want things to be modular.

**Comment by PabRod** [comment]
I see.

> do you think it would help to have a YAML snippet with example settings?

My main concern is that the code will crash for someone following the steps. This puts the users of the materials, both trainers and trainees, in a difficult situation; it may even be a problem regarding moving to beta phase. If a YAML snippet solves this, I will consider using it. The next question would be, does this completely solve the problem, or just postpones it until we introduce the ports and messages?

PS: talking about modularity, I am positively impressed by the cleanliness and usability of the theory behind this, and how it translates to the implementation. A project to be very proud of!

**Comment by LourensVeen** [comment]
Hmm, it sounds like this is a bit of a scripting vs. programming issue maybe. If you try to run only the contents of the `reaction` function, then it's going to crash anyway because there's no `initial_state` variable. You need to finish it, and then call it (in the original version) or have MUSCLE3 call it (in the version you're making out of it). MUSCLE3 will then provide the context it needs to run in. So you can't really do this interactively one line at a time, also because you need something else to be running in parallel to send and receive messages. [1]

So a coupled simulation is definitely programming, at least if you do it like this. The alternative is to use a system like AMUSE, where everything is driven from a Python script. There too however you need to deal with external components that have a state, so you may need to explicitly reset things. And it makes the whole thing single-threaded, which is not so efficient. On an HPC cluster, MUSCLE3 can start different submodels on different cores or nodes, so that different parts of the simulation can run in parallel. I'm planning to have it optimise in the future, e.g. put submodels that communicate a lot of data between them close together.

[1] There are ways to run individual submodels under a debugger, at which point you can single-step through them, but that uses the distributed execution mode. For the all-in-one-Python-script mode we use here, I don't know what something like VSCode does if you run the finished simulation in single-step mode. What actually happens is that two background processes are spun up that execute the models, and I don't know if or how it would deal with that.


I can't take credit for the theory (that goes to Joris Borgdorff, also Bastien Chopard and Alfons Hoekstra) but the API design is mine, thank you :smile:.

**Comment by PabRod** [comment]
And this is why it is great to have direct access to the author.

Thanks a lot for your detailed explanation :)
